version: '3.4'
services:
    nginx:
        image: nginx:1.13.6-alpine
        hostname: nginx
        ports:
            - 3000:80/tcp
        networks:
            wordpress:
                aliases:
                    - nginx
        volumes:
            - /nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /nfs/xbclub/www:/var/www/html:rw
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 3
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.role == worker
                    - node.hostname != Docker-Swarm-MySQL
                    - node.hostname != Docker-Swarm-Redis
                    - node.hostname != Docker-Swarm-NFS
                    - node.hostname != Docker-Swarm-Zabbix
                    - node.hostname != Docker-Swarm-Splunk
                    - node.hostname != Docker-Swarm-Indexer01
                    - node.hostname != Docker-Swarm-Indexer02
    wordpress:
        image: wordpress:4.9.1-php7.0-fpm
        hostname: php
        networks:
            wordpress:
                aliases:
                    - wordpress
        environment:
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=root
            - WORDPRESS_DB_NAME=xbclub
            - WORDPRESS_TABLE_PREFIX=wp_
        volumes:
            - /nfs/xbclub/www:/var/www/html:rw
            - /nfs/xbclub/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 3
            update_config:
                parallelism: 1
                delay: 10s
            placement:
                constraints:
                    - node.role == worker
                    - node.hostname != Docker-Swarm-MySQL
                    - node.hostname != Docker-Swarm-Redis
                    - node.hostname != Docker-Swarm-NFS
                    - node.hostname != Docker-Swarm-Zabbix
    mysql:
        image: mysql:5.7.20
        hostname: mysql
        networks:
            wordpress:
                aliases:
                    - mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - /mysql/xbclub:/var/lib/mysql
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == Docker-Swarm-MySQL
        logging:
            driver: json-file
            options:
                max-file: '3'
                max-size: 100m

    redis-haproxy:
        image: haproxy:1.8.3-alpine
        hostname: redis-haproxy
        networks:
            wordpress:
                aliases:
                    - redis-haproxy
        volumes:
            - /nfs/xbclub/redis/redis-haproxy:/usr/local/etc/haproxy:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == worker
    redis-master:
        image: redis:4.0.6
        hostname: redis-master
        networks:
            wordpress:
                aliases:
                    - redis-master
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.hostname == Docker-Swarm-Redis
    redis-slave:
        image: redis:4.0.6
        hostname: redis-slave
        command: redis-server --slaveof redis-master 6379
        networks:
            wordpress:
                aliases:
                    - redis-slave
        volumes:
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == worker
    redis-sentinel:
        image: redis:4.0.6
        hostname: redis-sentinel
        command: redis-sentinel /etc/redis/sentinel.conf --sentinel
        networks:
            wordpress:
                aliases:
                    - redis-sentinel
        volumes:
            - ./redis/redis-sentinel/sentinel.conf:/etc/redis/sentinel.conf:ro
            - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints:
                    - node.role == worker
networks:
    wordpress:
        external: true
